defaults:
  - _self_
  - task: mirrorduo

# ================================================
#       MirrorDuo Essential Hyperparameters 
# ================================================
enable_mirror: False     
enable_overlay: False
action_mode: null
pretrained: False
seed: 0
# ================================================

name: bc_rnn
_target_: mirrorduo.workspace.train_robomimic_image_workspace.TrainRobomimicImageWorkspace


shape_meta: ${task.shape_meta}
exp_name: "default"

task_name: stack_d1
n_demo: 200
horizon: &horizon 10
n_obs_steps: 1
n_action_steps: 1
n_latency_steps: 0
dataset_obs_steps: *horizon
past_action_visible: False
dataset: mirrorduo.dataset.robomimic_replay_image_mirrorduo_dataset.RobomimicReplayMirrorDuoImageDataset
dataset_path: data/${task_name}/${task_name}_mirrorduo.hdf5
n_envs: 56
env_name: null

policy:
  _target_: mirrorduo.policy.robomimic_image_policy.RobomimicImagePolicy
  shape_meta: ${shape_meta}
  algo_name: bc_rnn
  obs_type: image
  # oc.select resolver: key, default
  task_name: ${oc.select:task.task_name,lift}
  dataset_type: ${oc.select:task.dataset_type,ph}
  crop_shape: [76, 76]
  pretrained: ${pretrained}

dataloader:
  batch_size: 128
  num_workers: 8
  shuffle: True
  pin_memory: True
  persistent_workers: True

val_dataloader:
  batch_size: 128
  num_workers: 8
  shuffle: False
  pin_memory: True
  persistent_workers: True

robo_augmentor:
  mirror:
    enable: ${enable_mirror}
    prob: 0.5
    mode: "batch_wise"

  overlay:
    enable: ${enable_overlay}
    prob: 0.5
    warmup_epochs: ${eval:'4000 / ${n_demo}'}
    input_shape: [84, 84]
    blend_alpha: 0.75
    background_path: 'data/backgrounds'

training:
  device: "cuda:0"
  seed: ${seed}
  debug: False
  resume: True
  # optimization
  num_epochs: ${eval:'50000 / ${n_demo}'}
  # training loop control
  # in epochs
  rollout_every: 10
  checkpoint_every: 10
  val_every: 5
  sample_every: 5
  # steps per epoch
  max_train_steps: null
  max_val_steps: null
  # misc
  tqdm_interval_sec: 1.0

logging:
  project: ${task_name}_seed_${seed}
  resume: True
  mode: online
  name: ${name}_${n_demo}_${action_mode}_mirror_${enable_mirror}_overlay_${enable_overlay}_pretrained_${pretrained}
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: test_mean_score
    mode: max
    k: 3
    format_str: 'epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False

multi_run:
  run_dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: experiments/mirrorduo/${task_name}_seed_${seed}/${name}_${n_demo}_${action_mode}_mirror_${enable_mirror}_overlay_${enable_overlay}_pretrained_${pretrained}
  sweep:
    dir: experiments/mirrorduo/${task_name}_seed_${seed}/${name}_${n_demo}_${action_mode}_mirror_${enable_mirror}_overlay_${enable_overlay}_pretrained_${pretrained}
    subdir: ${hydra.job.num}
